### PR TITLE
jsrepl.js needs to be executed before exercises.js

### PR DESCRIPTION
**Pull request by ajblum**
Change to address https://github.com/GitbookIO/plugin-exercises/issues/6

### CODE REVIEW

**Comment by dnlkoch** [comment]
Is there anything missing for accepting this PR? We ran into the same issue mentioned in #6.

Thanks!

**Comment by marcjansen** [comment]
Can something be done to get this (or another appropriate change) in?

**Comment by marcjansen** [comment]
I have published a temporary plugin which includes the fix by @ajblum.

Just reference 

```
{
    "plugins": ["exercises-tmp-fixed-6"]
}
```
Here is the source: https://github.com/marcjansen/plugin-exercises

**I don't intend to maintain this temporary plugin and hope it becomes obsolete soon**

**Comment by Soreine** [comment]
@marcjansen The issue #6 has been fixed in master. Let us know if you're still encountering an issue.

**Comment by marcjansen** [comment]
Thanks for coming back to this. I'll see if I find time to test this.

**Pull request closed without merging**
